CREATE TABLE IF NOT EXISTS users (
    username    VARCHAR(50) PRIMARY KEY NOT NULL UNIQUE,
    password    VARCHAR(50)     NOT NULL,
    created_at  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP
);
